name: DVPL-9114 CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        node:
          - 14
        os:
          - ubuntu-latest
#           - windows-latest
#           - macos-latest
        splunk:
#           - 8.0
          - latest
          
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Create .splunkrc file
        run: |
          cd ~
          echo host=localhost > .splunkrc
          echo port=8089 >> .splunkrc
          echo username=admin >> .splunkrc
          echo password=changed! >> .splunkrc
          echo scheme=https >> .splunkrc
          echo version=${{ matrix.splunk }} >> .splunkrc
          cat .splunkrc
          pwd
      
      - name: Spin up a splunk container
        run: docker-compose up -d
        
      - name: Sleep
        uses: jakejarvis/wait-action@master
        with:
          time: '60s'
          
      - name: Use node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
    
      - name: Run server tests
        run: |
          pwd
          node sdkdo tests

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo testing Github Actions 2
