name: JS SDK

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node:
          - 14
        splunk-version:
          - "8.0"
          - "latest"
          
    runs-on: ${{ matrix.os }}
    
    services:
      splunk:
        image: splunk/splunk:${{matrix.splunk-version}}
        env:
          SPLUNK_START_ARGS: --accept-license
          SPLUNK_HEC_TOKEN: 11111111-1111-1111-1111-1111111111113
          SPLUNK_PASSWORD: changed!
          SPLUNK_APPS_URL: https://github.com/splunk/sdk-app-collection/releases/download/v1.0.0/sdk-app-collection.tgz
        ports:
          - 8000:8000
          - 8088:8088
          - 8089:8089
          
    steps:
      - uses: actions/checkout@v2
      
      - name: Use node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          
      - name: Create .splunkrc file
        run: |
          cd ~
          echo host=localhost > .splunkrc
          echo port=8089 >> .splunkrc
          echo username=admin >> .splunkrc
          echo password=changed! >> .splunkrc
          echo scheme=https >> .splunkrc
          echo version=${{ matrix.splunk }} >> .splunkrc
        
#       - name: Spin up a splunk container
#         run: |
#           SPLUNK_VERSION=${{ matrix.splunk }} make up
        
#       - name: Wait for container to spin up
#         uses: jakejarvis/wait-action@master
#         with:
#           time: '60s'
          
      
    
      - name: Run server tests
        run: node sdkdo tests
        env:
          SPLUNK_HOME: /opt/splunk
